### ISSUE TITLE
feat: Simulation hypothesis testing

### ISSUE THREAD

**Issue by jc2959** [GPIG-Team-A/Control-Centre#6]
The decision centre should perform 2000 trials of the rover one the given course, simulating the rover's motors to be slightly random, with their mean and standard deviation being calculated beforehand. The success result of a trial will be if the rover navigates the course without driving through an obstacle. The total amount of failed trials will be counted up and used in a hypothesis test.

The hypothesis test will check whether the chance of the rover failing a task is below a user defined p%. It will do this by comparing the amount of failed trials against a critical value, x. The critical value is the range of trial amounts such that if the probability of a trial failure is p% then the probability of there being 0 to x failed trials in 2000 is 5% - this probability is low enough that there is evidence supporting the idea that the chance of success is below p%.

Therefore, we can use these simulated trials to test whether the given path through the course is suitable for the physical rover to navigate

**Comment by jc2959** [comment]
Currently the backend of this issue has been developed, all that is left is to integrate it with the new UI

**Comment by DevonDF** [comment]
@jc2959 Does PR #22 finish this issue?

**Comment by jc2959** [comment]
Should do
